
package com.soa_study.main;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldStudent", targetNamespace = "http://service.soa_study.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldStudent {


    /**
     * 
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.soa_study.com/", className = "com.soa_study.service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.soa_study.com/", className = "com.soa_study.service.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "userName", targetNamespace = "")
        String userName);

    /**
     * 
     * @param lista
     * @return
     *     returns com.soa_study.service.GetStudentListResponse.Students
     */
    @WebMethod
    @WebResult(name = "Students", targetNamespace = "")
    @RequestWrapper(localName = "getStudentList", targetNamespace = "http://service.soa_study.com/", className = "com.soa_study.service.GetStudentList")
    @ResponseWrapper(localName = "getStudentListResponse", targetNamespace = "http://service.soa_study.com/", className = "com.soa_study.service.GetStudentListResponse")
    public com.soa_study.main.GetStudentListResponse.Students getStudentList(
        @WebParam(name = "Lista", targetNamespace = "")
        String lista);

    /**
     * 
     * @param studentSurname
     * @param studentName
     * @param studentPesel
     * @return
     *     returns com.soa_study.service.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://service.soa_study.com/", className = "com.soa_study.service.GetStudent")
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://service.soa_study.com/", className = "com.soa_study.service.GetStudentResponse")
    public Student getStudent(
        @WebParam(name = "studentName", targetNamespace = "")
        String studentName,
        @WebParam(name = "studentSurname", targetNamespace = "")
        String studentSurname,
        @WebParam(name = "studentPesel", targetNamespace = "")
        String studentPesel);

}
